version: '3.8'

services:
  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: runner
    restart: unless-stopped
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api
    depends_on:
      - api

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: runtime
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - PORT=8000
      - FRONTEND_URL=http://localhost:4000

networks:
  default:
    name: app-test-network 