# .github/workflows/deploy.yml
name: Deploy to Oracle VM

on:
  push:
    branches: [main]        # auto-deploy every successful push to main
  workflow_dispatch:        # allow a manual "Run workflow" button

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20     # prevent hung jobs

    steps:
    # 1) check out repo
    - uses: actions/checkout@v4

    # 2) SSH and run the deployment commands using appleboy/ssh-action
    - name: Deploy
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        script: |
          set -e
          cd ~/my-site
          echo "▶ pulling latest code…"
          git pull origin main
          echo "▶ pulling latest images…"
          docker compose -f docker-compose.prod.yml pull
          echo "▶ recreating stack…"
          docker compose -f docker-compose.prod.yml up -d
          echo "✅ deploy complete"
