# .github/workflows/deploy.yml
name: Deploy to Oracle VM

on:
  push:
    branches: [main]        # auto-deploy every successful push to main
  workflow_dispatch:        # allow a manual "Run workflow" button

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20     # prevent hung jobs

    steps:
    # 1) check out repo
    - uses: actions/checkout@v4

    # 2) Set up SSH key using the simpler webfactory/ssh-agent action
    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    # 3) Add server to known hosts
    - name: Add known hosts
      run: ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

    # 4) SSH and run the deployment commands
    - name: Deploy
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          set -e
          cd ~/my-site
          echo "▶ pulling latest code…"
          git pull origin main
          echo "▶ pulling latest images…"
          docker compose -f docker-compose.prod.yml pull
          echo "▶ recreating stack…"
          docker compose -f docker-compose.prod.yml up -d
          echo "✅ deploy complete"
